### ISSUE TITLE
Suggestion: Forfeit function

### ISSUE THREAD

**Issue by RuiNtD** [midoshouse/ootr-multiworld#15]
Since [the usual Lua codes for when players forfeit](https://pidgezero.one/zootr/mwlua.html) require the official MW script, is it possible to add a function for players to forfeit, automatically sending their remaining checks to the other players? This function could either show up for the individual players or only for player 1. This may require uploading the spoiler log, but that could also be used to verify that you, in fact, are the "host" of your lobby or otherwise have permission to forfeit.

**Comment by fenhl** [comment]
Yes, this is definitely something I want to add, in fact it's already in progress! It's currently only available to me personally through the admin console, and has been tested a few times. The current plan for how it will work is that unless the room is tagged as a tournament room (#6), any player can upload the spoiler log and select a player whose items will be sent out. There are two remaining blockers before it can be made generally available:

- [ ] It needs to be fixed to work with different versions of the randomizer. Currently it's hardcoded to version 6.2.181.
- [ ] The feature needs to be added to the user interface. I ran into a weird BizHawk crash the last time I attempted this.

**Comment by FayneAldan** [comment]
> The feature needs to be added to the user interface. I ran into a weird BizHawk crash the last time I attempted this.

Is it possible to add features via a website (like on midos.house) if you fail to get it working in the GUI?
A website could also be used to provide an auto-tracker (#7) or provide backup downloads for #5.

**Comment by fenhl** [comment]
The crash is just programmer error, there's no real reason it can't work in the GUI.

**Comment by fenhl** [comment]
The version is now read from the spoiler log and no longer hardcoded to 6.2.181, but I still need to have the server download the randomizer version if it's not already present.
