### ISSUE TITLE
Support co-op context changes on Dev-Rob

### ISSUE THREAD

**Issue by Murphy0749** [midoshouse/ootr-multiworld#34]
Hello, I wanted to play multiworld with my friend and we could not receive any items that were in our other worlds. My friend got an ice trap for me and I could not get it. We were using the dev build for Rob v7.1.195 so idk if it had something to do with that. We also had settings like Silver Rupee shuffle, all Adult trade items, and a somewhat light entrance shuffle if it had to do with that.

Please help as soon as possible.

**Comment by fenhl** [comment]
This was discussed on Discord and the version being used is 7.1.195 Rob-49. Versions 7.1.195 Rob-46 and higher include https://github.com/OoTRandomizer/OoT-Randomizer/pull/2069 which is an unversioned change to the co-op context. I could add support for it anyway by checking the randomizer version and [branch identifier](https://wiki.ootrandomizer.com/index.php?title=Branch_identifiers). Turning this issue into a tracking issue for that.

**Comment by fenhl** [comment]
See also https://github.com/rrealmuto/OoT-Randomizer/pull/85.
