### ISSUE TITLE
A computed CRC32 value did not match the expected value

### ISSUE THREAD

**Issue by Braumski** [midoshouse/ootr-multiworld#46]
error while trying to update Mido's House Multiworld from version 16.0.1:
a computed CRC32 value did not match the expected value
```rust
Zip(CRC32CheckError)
```

**Comment by fenhl** [comment]
Unable to reproduce. Can you check if it happens again if you open the multiworld app again? Also which console/emulator are you using?

**Comment by fenhl** [comment]
@Braumski also contacted me on Discord. This issue is happening with BizHawk on Windows, where I can also reproduce it. Anyone affected by this can install the newest version from <https://midos.house/mw> as a workaround — no need to uninstall the old version or anything.
